[GEN-474, GEN-500, GEN-721, GEN-379] Include data guide generation in nextflow scripts
Sage-Bionetworks-Workflows/nf-genie pull request #4
Opened 2023-03-17 08:06 UTC by thomasyu888

- Add in new quarto tool that generates the data guide.
- Add create data guide to nextflow step
- This was tested on both consortium and public within nextflow tower

Next step is to deprecate data guide generation from GENIE python package

2023-07-12 21:17 UTC, Chelsea-Na requested changes
Wow, looks great.

Please see my comments

2023-07-12 21:17 UTC, Chelsea-Na commented on scripts/data_guide/data_guide.qmd
> +* Description: Segmented copy number data. Note: Not all centers contributed copy number data to GENIE
A SEG file (segmented data; .seg or .cbs) is a tab-delimited text file that lists loci and associated numeric values.

2023-07-13 01:45 UTC, thomasyu888 commented on scripts/data_guide/data_guide.qmd
> +}
Made this "Not Available"

2023-07-13 02:00 UTC, Chelsea-Na commented on scripts/data_guide/data_guide.qmd
> +* Data Description: The primary cancer diagnosis "main type", based on the OncoTree ontology. The version of Oncotree ontology that was used for GENIE 13.0-public is oncotree_2021_11_02
Update to use the release name parameter and to link out to the specific oncotree code

2023-07-14 14:54 UTC, merged